# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# Site settings
url: 'https://www.chengbutang.com'
baseurl: ''
title: 'ChengBuTang'
description: '成步堂专注正版模玩'
permalink: pretty
logo: "https://img.alicdn.com/imgextra/i2/2710706468/O1CN01bF11cs1xeOUc1IXH1_!!2710706468.jpg"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: 首页
  url: /
- title: 关于
  url: /about/
- title: 联系
  url: /contact/
- title: 博客
  url: /blog/

# Footer nav
navigation_footer:
- title: 返回顶部↑Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: 博客
    output: true
    description: "请添加微信ID：320297254并留意朋友圈更新"
    feature_text: 
    feature_image:https://img.alicdn.com/imgextra/i1/2710706468/O1CN01aVgsBk1xeOUswfxx6_!!2710706468.jpg

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
